#!/bin/sh

: "${DBUS_SESSION_BUS_ADDRESS:=unix:path=${XDG_RUNTIME_DIR}/bus}"

exec dbus-daemon --session --nofork --nopidfile --address=${DBUS_SESSION_BUS_ADDRESS} --print-pid=3 --print-address=4 2>1 4> ${XDG_RUNTIME_DIR}/env/DBUS_SESSION_BUS_ADDRESS
